#requires -Version 7
<#
  PreToolUse hook (Claude Code).

  WHY: data/addizionali/comuni-<anno>.json are GENERATED by tools/AddizionaliImporter
  (elenco comuni ISTAT + tabella aliquote MEF). A hand-edit there is silently lost on
  the next regeneration, so this hook blocks direct edits and points back to the importer.

  PROTOCOL: receives the tool event as JSON on stdin; reads tool_input.file_path.
  Exit 0 = allow. Exit 2 = deny the edit (reason on stderr is surfaced to Claude).
  NOTE: the reason is written via [Console]::Error.WriteLine (not Write-Error) so that
  $ErrorActionPreference='Stop' does not turn it into a throw that masks the exit code.
#>

$ErrorActionPreference = 'Stop'

try {
    $event = [Console]::In.ReadToEnd() | ConvertFrom-Json
    $path  = $event.tool_input.file_path
} catch {
    exit 0   # not a parseable file event -> allow
}

if (-not $path) { exit 0 }

$norm = $path -replace '\\', '/'
if ($norm -match '(?i)data/addizionali/comuni-\d+\.json$') {
    $file = [System.IO.Path]::GetFileName($path)
    [Console]::Error.WriteLine(@"
[hook] BLOCKED: $file is GENERATED, not hand-maintained.
Source: tools/AddizionaliImporter (elenco comuni ISTAT + tabella aliquote MEF) - see tools/README.md.
A manual edit here is overwritten on the next regeneration.
  -> To change comuni data, update the importer inputs and regenerate.
  -> For a single missing comune, enter its aliquota manually in-app (the UI supports it).
"@)
    exit 2
}

exit 0
